---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: ${CONTAINER_NAME:-syncthing}
    #hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - /etc/timezone:/etc/timezone:ro  
      - ${PATH_CONFIG:-/var/docker/config/syncthing}:/config  
      - ${PATH_DATA1:-/var/docker/data/syncthing/data1}:/data1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
