---
version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro    
      - /etc/timezone:/etc/timezone:ro  
      - ${PATH_CONFIG:-/var/docker/config/heimdall}:/config  
    ports:
      - ${PORT_HTTP:-7021}:80
    restart: unless-stopped